Create a function named calculate() in mean_var_std.py that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

The input of the function should be a list containing 9 digits. The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.

In [1]:
import numpy as np
import pandas as pd

In [59]:
def calculate(a):
    if len(a) < 9:
        raise ValueError ('List must contain 9 numbers')
    else:
        x = np.reshape(a,(3,3))
        
        d ={'mean':[np.mean(x,0), np.mean(x,1), np.mean(x)],
            'variance': [np.var(x,0), np.var(x,1), np.var(x)],
            'standard deviation': [np.std(x,0), np.std(x,1), np.std(x)],
            'max' : [np.max(x,0), np.max(x,1), np.max(x)],
            'min' : [np.min(x,0), np.min(x,1), np.min(x)],
            'sum' : [np.sum(x,0), np.sum(x,1), np.sum(x)]}
    return d

In [60]:
#x = np.reshape(list_data, (100, 28)).T
a = [0,1,2,3,4,5,6,7,8]
calculate(a)

{'mean': [array([3., 4., 5.]), array([1., 4., 7.]), 4.0],
 'variance': [array([6., 6., 6.]),
  array([0.66666667, 0.66666667, 0.66666667]),
  6.666666666666667],
 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611],
 'max': [array([6, 7, 8]), array([2, 5, 8]), 8],
 'min': [array([0, 1, 2]), array([0, 3, 6]), 0],
 'sum': [array([ 9, 12, 15]), array([ 3, 12, 21]), 36]}

In [61]:
a = [10,11,12,13,14,15,16,17,18]
calculate(a)

{'mean': [array([13., 14., 15.]), array([11., 14., 17.]), 14.0],
 'variance': [array([6., 6., 6.]),
  array([0.66666667, 0.66666667, 0.66666667]),
  6.666666666666667],
 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611],
 'max': [array([16, 17, 18]), array([12, 15, 18]), 18],
 'min': [array([10, 11, 12]), array([10, 13, 16]), 10],
 'sum': [array([39, 42, 45]), array([33, 42, 51]), 126]}

In [62]:
a = [1,2,3,4,5]
calculate(a)

ValueError: List must contain 9 numbers